USE [master]
GO

/****** Object:  Database [Population]    Script Date: 09.10.2015 22:11:53 ******/
CREATE DATABASE [Population]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'World', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\World.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'World_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\World_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Population] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Population].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Population] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Population] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Population] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Population] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Population] SET ARITHABORT OFF 
GO

ALTER DATABASE [Population] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Population] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Population] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Population] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Population] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Population] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Population] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Population] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Population] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Population] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Population] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Population] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Population] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Population] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Population] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Population] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Population] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Population] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Population] SET  MULTI_USER 
GO

ALTER DATABASE [Population] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Population] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Population] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Population] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Population] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Population] SET  READ_WRITE 
GO

